### ISSUE TITLE
Improve the Rollups senders list with a "move" to another Rollup option and better UX for the "remove" option

### ISSUE THREAD

**Issue by dinkydani** [leavemealone-app/roadmap#23]
- [x] Add a "move" option to remove from this/add to another Rollup
- [x] Allow bulk removing/moving with checkboxes in the UI

**Comment by Jivings** [comment]
As a first pass lets put a "move" button here that opens the Rollup dropdown

<img width="1019" alt="image" src="https://user-images.githubusercontent.com/1462828/164633682-c89776d1-670e-46b2-b648-50c47ed92b96.png">
