### ISSUE TITLE
Use text terms (rather than just senders) to specify priority

### ISSUE THREAD

**Issue by momorgan** [leavemealone-app/roadmap#40]
Priority Senders works flawlessly. But sometimes a whitelistable email is better identified by search terms such as keywords in the subject line, rather than a specific sender.

Use case:
Let's say I was buying a flat. Lots of different senders are likely to message me—my lawyer, seller's lawyer, estate agent, surveyor, freeholder, electrician, removals, insurer, so on and so on. All of whom are easy to identify by subject line but hard to identify by sender, and all would want to be whitelisted.

Use case:
Let's say I was emailing customers. I'd likely use a particular turn of phrase in my subject line, let's say 'Extruded Plastic Dingus support'. If I wanted their responses ASAP, I could add this term to my priority list and their replies would be whitelisted even though they'd all be coming from different senders.

**Comment by Jivings** [comment]
You're right 100%, this needs doing.

We've also had multiple requests for us to let through things like verification emails and I think this is also how we will solve that problem.

We'll provide a few default terms for verification emails and such, and also allow you to add your own custom ones. This will require us to create a slightly more complex filtering system on our end, so is not a quick fix, but it's definitely priority on the roadmap.

Thanks!

**Comment by momorgan** [comment]
Yep, I'd forgotten about verification emails. I've experienced that: very valid case.

Kinda the opposite is true too: I'd *always* want to roll up, say, "see what you missed" from LinkedIn but perhaps keep everything that comes from messages-noreply@linkedin.com

**Comment by Jivings** [comment]
Yeah so if we imagine that the system works like this: `filter => action`

Currently `filter` is always just a email address or domain, and `action` is always rollup, block or allow. 
We could adapt it so that filter could be specified by you to either be email/domain or a complex filter where you can specify matching text in the subject or body of the email.

I think that solves 99% of use cases.

**Comment by vertis** [comment]
This makes a lot of sense to me. Having a subject filter allows advertising it briefly, say on a job ad, and then retracting it later.

I think complex filters could be a very nice feature, and I'm sure people can find interesting ways of applying them.

**Comment by momorgan** [comment]
Oh yes, superpowered filters would be amazing, particularly for non-gmail users whose host-supplied filters are a bit... agricultural. Some basic operators, at least, would be a much better way to sort incoming mail - not only into rollups etc but also folders. I feel like I'm feature-creeping though...

**Comment by Jivings** [comment]
Haha yes, I think a dedicated "Filters" page will be the final state of this, but for now I'm going to add custom filters to the Priority Senders feature as I think that will cover most problems with the screener that people are having right now.

**Comment by Jivings** [comment]
@momorgan, I just shipped this so you should be able to add Filters to priority senders now :)

<img width="666" alt="image" src="https://user-images.githubusercontent.com/1462828/166425239-70ff553f-e7a5-45bf-bd7f-8c4f65f43c32.png">

Let me know if you have any issues with it!

**Comment by Jivings** [comment]
You should see the filter details in the History view too so you can debug it if it doesn't look to be working correctly

<img width="875" alt="image" src="https://user-images.githubusercontent.com/1462828/166426967-c10579be-6695-4a61-8474-6be5356004d6.png">

**Comment by momorgan** [comment]
Ooh look at that, this is excellent! I've set up some (boring) search terms for MFA codes and whatnot, so hopefully it won't be long before I see it in action.

Thanks @Jivings - I think this is going to be pretty impactful.

**Comment by Jivings** [comment]
Fantastic. I think next step we'll add some "tips" or examples at the top of the priority senders page that will suggest filters you can add for that sort of thing.
