### ISSUE TITLE
Option to whitelist or rollup replies to emails in sent folder

### ISSUE THREAD

**Issue by momorgan** [leavemealone-app/roadmap#41]
Replies to emails I've sent are a different use-case from 'new' emails. It'd be great to be able to separate the handling of these. 

With new emails it makes sense to block/screen all, apart from those whitelisted. With replies, it'd be good to have the option either to whitelist those I've sent emails to, perhaps by automatically building a 'sent whitelist' from sweeping the sent folder.

Use case:
Let's say I email my member of parliament on an important issue. I could then add the address I emailed to the priority senders list, but there's no guarantee she will reply at all, plus it adds a step. But if she does reply, I might want that reply sooner than, say, whatever other stupid 'new' emails I get that day.

**Comment by Jivings** [comment]
There's actually an option for this already, I think it should be enabled by default but in your case perhaps it was disabled.

<img width="583" alt="image" src="https://user-images.githubusercontent.com/1462828/164433284-d5e9cfca-7f33-4e2e-a7c6-73adfca0c452.png">

Does that solve this problem?

**Comment by momorgan** [comment]
Oh! Hmm. That's interesting, because I don't think that is working in my case—the option is selected but I'm _fairly_ sure replies are being screened. I'll investigate more and find a specific example.

**Comment by Jivings** [comment]
Let me know if you find anything, I'll close this ticket for now ✨

**Comment by momorgan** [comment]
Hi, yes I have found a specific example of this now. I've got an email where someone is replying to one I've sent, and yet it's sitting in screened mail.

**Comment by Jivings** [comment]
Can you find it in your history view? Can you send me the ID that's in there please and I can check it out.

**Comment by momorgan** [comment]
Yeah why didn't i think of that? Sorry.

67a98d11-8e20-4d65-8fb8-645ef6e63886

**Comment by Jivings** [comment]
Yep can see it was blocked, the screener thought it wasn't a reply. All we do is check if the email has an "in-reply-to" header:

<img width="492" alt="image" src="https://user-images.githubusercontent.com/1462828/166693175-f0fd2133-101b-413a-9763-cd3025e7a3d4.png">

Do you know how to check the email headers? I would guess that this does not have the right header! It should get added by the sender/replier, so I guess whatever email client they use does not add it.

**Comment by momorgan** [comment]
Yes, it does. Their client looks kinda Outlookish to me.

![Screenshot 2022-05-04 at 17 46 14](https://user-images.githubusercontent.com/223823/166734010-7fd48217-567b-407f-b723-d7e4093b02ff.jpg)

**Comment by Jivings** [comment]
Sorry we weren't passing the option `alwaysAllowReplies` between the functions properly 🤦‍♂️ 

It should be fixed now!
