### ISSUE TITLE
Progressive web app

### ISSUE THREAD

**Issue by momorgan** [leavemealone-app/roadmap#42]
LMA works really well responsively. It's one small step away from being a lovely webapp: one that users could add to their (mobile) homescreen and stick the icon next to their mail client. Useful while onboarding, but also reducing friction when that critical email comes though from an unknown source. Currently it's kinda fugly.

**Comment by Jivings** [comment]
This is now available (in it's most basic form). 

You should now be able to install from your mobile browser when the app is logged in 👍

In future we can think about adding notifications for new screened mail or other events. 

Thanks for the push to do this @momorgan!

**Comment by momorgan** [comment]
Oh this is _much_ better. The icon (on iOS) perhaps needs a dusting down as the background colour is black (as opposed to the light yellow as per Android), but yes. Great!

**Comment by Jivings** [comment]
I don't have an iPhone, can you screenshot it for me? Not sure why it would appear black.

**Comment by momorgan** [comment]
I know right? Who even has an iPhone anymore ;)

But yeah, here you go:

![IMG_0081](https://user-images.githubusercontent.com/223823/164894891-1ed2dfb2-3430-4a8d-9177-ecf802550790.PNG)

**Comment by Jivings** [comment]
No idea why that happens 😅 if I get a chance then I'll check it out.

Hope you're enjoying the snooker!

**Comment by momorgan** [comment]
Not content with reading all my emails, now you're watching all my televisions

:D
