### ISSUE TITLE
Do-not-disturb overnight schedule

### ISSUE THREAD

**Issue by momorgan** [leavemealone-app/roadmap#46]
Right now it's impossible to set DND to, say, 7pm to 7am, because the scheduler says "Start time must be before end time".

Two ways to solve it: either always assume the second time is after the first. Or allow multiple schedules, which I think is already in the works, but the first is more elegant from the perspective of user expectation. Setting up two, back-to-back schedules (one for 7pm to midnight and another for midnight to 7am) feels awful hacky.

**Comment by Jivings** [comment]
You're right, @dinkydani is working on multiple schedules. It's probably a few weeks away though as we're smashing through a backlog of customer requests.

I think as part of this we'll change the "Weekends" preset to be "Evenings and Weekends", which will consist of multiple schedules. This gives the user a nice example of how the schedules can be set up.

**Comment by momorgan** [comment]
Yep, fair enough. By all means prioritise however you feel is most appropriate. Damn customers and their damn requests ;)

**Comment by Jivings** [comment]
Hey @momorgan, this is now ready and you can add a total of 3 schedules! Sorry for the delay!
