### ISSUE TITLE
Snooze button

### ISSUE THREAD

**Issue by Jivings** [leavemealone-app/roadmap#58]
Add snooze capability to senders in the screener.

When we screen an email, the customer should be able to choose to snooze it from the screener view. Either until the next time it's seen, or for a specific time period (eg 1 week, 1 month, 1 year). While snoozed the email will still be screened, but wont show in the "new" column until after the snooze has finished.

**Comment by sharad-teracube** [comment]
Would love this feature. This way I won't loose those senders forever but can still mute them for some time.

**Comment by Jivings** [comment]
@sharad-teracube this is now live! ✨

**Comment by sharad-teracube** [comment]
Love the quick addition. Will use it and let you know any feedback.
