### ISSUE TITLE
Web UI slow / CPU intensive

### ISSUE THREAD

**Issue by sharad-teracube** [leavemealone-app/roadmap#59]
I use a relatively beefy i5 pc and all other websites work quick/snappy. However, leavemealone.app is slow to respond to clicks and feels very sluggish most times. CPU usage also goes up (for the initial 5-10 seconds it seems). Is this a known issue?

**Comment by sharad-teracube** [comment]
Issue happening on Chrome. Edge works fine - switched to Edge just for leavemealone :).

**Comment by Jivings** [comment]
Hey @sharad-teracube, I've no idea why this would be happening. Was it during a scan for mail or just constantly?

Haven't had any other reports of this, so maybe it was just one release that we had. Can you try it again?

**Comment by sharad-teracube** [comment]
Hi James,

Somehow my chrome continues to be slow for the first 4-5 seconds of loading
leavemealone. Edge on the other hand is smooth right after load. Could be
something specifically on my computer. Not sure what though. Feel free to
close this issue.

--
Sharad Mittal
Founder and CEO
*Teracube - Environmentally Conscious Electronics*
Learn more at myteracube.com

**Comment by Jivings** [comment]
Thanks for the update! I'll leave this open for now in case anyone else reports!

**Comment by dinkydani** [comment]
I'm closing this as lots has changed since this bug was raised and no-one else has reported it so far :)
