### ISSUE TITLE
How to clear old "Screened email"

### ISSUE THREAD

**Issue by sharad-teracube** [leavemealone-app/roadmap#62]
There is such an option under Subscriptions. But the same is missing from Screened email.

**Comment by Jivings** [comment]
I'm not sure which option you mean @sharad-teracube. Can you screenshot?

**Comment by sharad-teracube** [comment]
![image](https://user-images.githubusercontent.com/70285625/194636136-5a5873fc-ebc9-44ae-9436-eb7365c7b8c5.png)

With the help of your new snooze buttons in screened - I'm able to clear out all my new screened emails. But I have a big old baggage of emails that were never snoozed. I will like to clear all the old ones so that my screened email list can be empty when I snooze or block my daily new emails.

**Comment by Jivings** [comment]
So you essentially want to delete all the ones that have status = "new" ?

**Comment by sharad-teracube** [comment]
Yes. However, I finally cleared all of them manually myself. So don't need it for me. But maybe good for other folks.

**Comment by Jivings** [comment]
Okay great!
