### ISSUE TITLE
Merge or Import Rollup contacts?

### ISSUE THREAD

**Issue by sharad-teracube** [leavemealone-app/roadmap#63]
I would like to merge my 3 rollups below. Is there a way for me to Merge all 3 rollups into one (combining all senders). Or a way for me to export, edit and Import back? I see export but no import.

![image](https://user-images.githubusercontent.com/70285625/194133816-db40622d-6863-44d6-bcd4-f19099afbe4c.png)

**Comment by Jivings** [comment]
There's no merge right now. However you can select the senders that you wish to "move" to a different Rollup from the senders screen. You just check the box and click the "move" button at the top right:

<img width="1116" alt="image" src="https://user-images.githubusercontent.com/1462828/194484201-de999bc2-0984-4747-891c-b20a9deb92de.png">

There's no way to select all the senders to move, so we'll make that an option!

**Comment by Jivings** [comment]
There's now a "select all" button so that you can move all the senders to another Rollup ✅

**Comment by sharad-teracube** [comment]
Super - will try it out soon. Thanks a ton 🥇
