### ISSUE TITLE
Always enabled action buttons

### ISSUE THREAD

**Issue by james-william-r** [leavemealone-app/roadmap#69]
Excl. unsubscribes, enable users to re-categorise senders by clicking any of the action buttons, without first having to de-select the current state.

<img width="457" alt="Screenshot 2023-04-08 at 11 58 40 am" src="https://user-images.githubusercontent.com/66140148/230717519-91bea6e8-828c-4dee-b8dc-33b5bd0a6e4d.png">

**Comment by dinkydani** [comment]
@james-william-r this is actually quite a bit of work, so I added tooltips over the disabled buttons to hint that you need to unselect the current value first. Please let me know if you still get a lot of support requests on this topic and I can re-open this issue :)
