### ISSUE TITLE
Increase Height of Rollup Selection Dropdown

### ISSUE THREAD

**Issue by james-william-r** [leavemealone-app/roadmap#71]
Requested by customer with lots of rollups: Wishes for the dropdown to be longer as keeps accidentally closing it when scrolling down to bottom of list.

![2023-05-11 5 26 36 pm](https://github.com/leavemealone-app/roadmap/assets/66140148/d18c1856-e687-40ec-a5c2-25040662e3b0)

**Comment by dinkydani** [comment]
Solved and confirmed by customer!
