### ISSUE TITLE
More granular control over do-not-disturb schedules 

### ISSUE THREAD

**Issue by james-william-r** [leavemealone-app/roadmap#73]
Currently, you can set multiple do-not-distrub schedules to one or all accounts.
- Customer would like be able to select multiple accounts.
- Additionally, we could add support for separate schedules for multiple account selections (eg. 1 schedule for email addresses A and B, another for C and D, and another for E).

**Comment by dinkydani** [comment]
Added the ability to select an account for each schedule instead of for all schedules. This solves both issues unless the customer has more than 3 accounts; in which case we could increase the schedules limit for this scenario. Closing because the main issue is resolved.
