### ISSUE TITLE
Screener: Allow Once

### ISSUE THREAD

**Issue by james-william-r** [leavemealone-app/roadmap#76]
To avoid blocking subscription confirmations, first-time order notifications, and with other important first-time emails, we should add an "allow once" option to the screener.

**Comment by dinkydani** [comment]
Ok so here's how this should work..
1. we get a new screened email (it will auto categorize as new if it's the first time the screener has seen it)
2. if it would be blocked by any rules then check if customer has "allow once" enabled
3. if "allow once" enabled then a) dont move it to blocked, b) add a label to show in the screener UI

**Comment by dinkydani** [comment]
![telegram-cloud-photo-size-4-5875208338726306506-y](https://github.com/leavemealone-app/roadmap/assets/3687223/31f6539e-9f29-4554-9056-41a469883e0a)

New setting in Shield -> Settings to allow the first email from a sender that isn't blocked by a blocklist.
