### ISSUE TITLE
"Not authorized" error upon successful password reset

### ISSUE THREAD

**Issue by james-william-r** [leavemealone-app/roadmap#84]
Happened for a couple of users. Password shows as successful on backend, and user is able to login successfully despite error.

![photo_2024-10-31 13 53 40](https://github.com/user-attachments/assets/c65378ef-e54d-4793-b2d4-11f70b4266b9)

**Comment by dinkydani** [comment]
I can't recreate this but based on the reports it looks like the login works and a refresh will work so I have added a catch for the reset flow that will try to redirect the user to the CMS once the reset is completed. If they aren't logged in by then they'll be redirected to login and that should work. Fingers crossed!

**Comment by james-william-r** [comment]
Seemed to be doing the job! - Closing for now.
